[build]
  base = "frontend-deployment-20251013_182159/"
  publish = "frontend-deployment-20251013_182159/"
  command = "echo 'Using pre-built frontend package'"

[build.environment]
  REACT_APP_API_URL = "https://beam-affiliate-backend.herokuapp.com"
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_STRIPE_PUBLIC_KEY = "pk_test_51234567890abcdefghijklmnopqrstuvwxyz1234567890"

[[redirects]]
  from = "/api/*"
  to = "https://beam-affiliate-backend.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
